#Pi Supply IoT LoRa Gateway Image
FROM resin/%%RESIN_MACHINE_NAME%%-debian:latest AS buildstep

WORKDIR /opt/iotloragateway/

RUN apt-get update
RUN apt-get install python3-dialog protobuf-compiler libprotobuf-dev libprotoc-dev automake libtool autoconf python-dev python-rpi.gpio git pkg-config protobuf-c-compiler libprotobuf-c-dev

COPY dev dev

RUN chmod +x ./dev/compile.sh
RUN ./dev/compile.sh

#Download apt packages required
